/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoraavancada;
import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author hugop
 */
public class CalculadoraInterface extends javax.swing.JFrame {
    int baseSelecionada = 0;
    
    /**
     * Creates new form CalculadoraInterface
     */
    public CalculadoraInterface() {
        setTitle("Conversor de base numérica");
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Button8_ = new javax.swing.JButton();
        Button5_ = new javax.swing.JButton();
        Button2_ = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        Button7_ = new javax.swing.JButton();
        Button4_ = new javax.swing.JButton();
        Button1_ = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        ButtonA = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        ButtonF = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        Button9 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonIgual = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonApagar = new javax.swing.JButton();
        ButtonLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonHex = new javax.swing.JButton();
        ButtonDec = new javax.swing.JButton();
        ButtonOct = new javax.swing.JButton();
        ButtonBin = new javax.swing.JButton();
        ResultadoOct = new javax.swing.JLabel();
        ResultadoDec = new javax.swing.JLabel();
        ResultadoHex = new javax.swing.JLabel();
        ResultadoBin = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button8_.setText("8");
        Button8_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8_ActionPerformed(evt);
            }
        });

        Button5_.setText("5");
        Button5_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5_ActionPerformed(evt);
            }
        });

        Button2_.setText("2");
        Button2_.setToolTipText("");
        Button2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button8_, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(Button5_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button2_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button8_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button5_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button2_))
        );

        Button7_.setText("7");
        Button7_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7_ActionPerformed(evt);
            }
        });

        Button4_.setText("4");
        Button4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4_ActionPerformed(evt);
            }
        });

        Button1_.setText("1");
        Button1_.setToolTipText("");
        Button1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button7_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button4_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button1_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button7_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button4_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button1_))
        );

        ButtonA.setText("A");
        ButtonA.setEnabled(false);
        ButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAActionPerformed(evt);
            }
        });

        ButtonB.setText("B");
        ButtonB.setEnabled(false);
        ButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBActionPerformed(evt);
            }
        });

        ButtonC.setText("C");
        ButtonC.setEnabled(false);
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonD.setText("D");
        ButtonD.setEnabled(false);
        ButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDActionPerformed(evt);
            }
        });

        ButtonE.setText("E");
        ButtonE.setToolTipText("");
        ButtonE.setEnabled(false);
        ButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEActionPerformed(evt);
            }
        });

        ButtonF.setText("F");
        ButtonF.setEnabled(false);
        ButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(ButtonD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonF))
        );

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button3.setText("3");
        Button3.setToolTipText("");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        ButtonIgual.setText("=");
        ButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(Button9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button3))
        );

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonApagar.setText("AP");
        ButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonApagarActionPerformed(evt);
            }
        });

        ButtonLimpar.setText("C");
        ButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(ButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button0))
        );

        ButtonHex.setText("HEX ");
        ButtonHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHexActionPerformed(evt);
            }
        });

        ButtonDec.setText("DEC");
        ButtonDec.setBorderPainted(false);
        ButtonDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecActionPerformed(evt);
            }
        });

        ButtonOct.setText("OCT");
        ButtonOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOctActionPerformed(evt);
            }
        });

        ButtonBin.setText("BIN");
        ButtonBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBinActionPerformed(evt);
            }
        });

        ResultadoOct.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ResultadoOct.setText("0");

        ResultadoDec.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ResultadoDec.setText("0");

        ResultadoHex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ResultadoHex.setText("0");
        ResultadoHex.setToolTipText("");

        ResultadoBin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ResultadoBin.setText("0");

        Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Status.setText("Convertendo decimal");
        Status.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonHex, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(ButtonDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonOct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonBin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ResultadoDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(ResultadoOct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResultadoBin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResultadoHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonHex)
                    .addComponent(ResultadoHex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDec)
                    .addComponent(ResultadoDec))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonOct)
                    .addComponent(ResultadoOct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBin)
                    .addComponent(ResultadoBin))
                .addGap(12, 12, 12)
                .addComponent(Status))
        );

        Resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Resultado.setText("0");
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
//    private void Operador(String caractere) {
//        String calculos = Calculos.getText();
//        String resultado = Resultado.getText();
//        
//        if(resultado.equals("0")) {
//           Calculos.setText("0".concat(caractere));
//        } else if(calculos.isEmpty()){
//            Calculos.setText(Resultado.getText().concat(caractere));
//        } else {
//           Calculos.setText(Calculos.getText().concat(Resultado.getText()).concat(caractere));   
//        }
//    }
    
    private void digita(String caractere) {
        String textoCalculos = Resultado.getText();
        if(Resultado.getText().equals("0")) {
                Resultado.setText(caractere);
           } else {
                Resultado.setText(Resultado.getText().concat(caractere));
           }
//        if(textoCalculos.isEmpty()) {
//           if(Resultado.getText().equals("0")) {
//                Resultado.setText(caractere);
//           } else {
//                Resultado.setText(Resultado.getText().concat(caractere));
//           }   
//        } else {
//            Resultado.setText(caractere);
//        }
    }
    
    private void Button8_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8_ActionPerformed
        digita("8");
    }//GEN-LAST:event_Button8_ActionPerformed

    private void Button5_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5_ActionPerformed
        digita("5");
    }//GEN-LAST:event_Button5_ActionPerformed

    private void Button2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2_ActionPerformed
        digita("2");
    }//GEN-LAST:event_Button2_ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        digita("0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button7_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7_ActionPerformed
        digita("7");
    }//GEN-LAST:event_Button7_ActionPerformed

    private void Button4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4_ActionPerformed
        digita("4");
    }//GEN-LAST:event_Button4_ActionPerformed

    private void Button1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1_ActionPerformed
        digita("1");
    }//GEN-LAST:event_Button1_ActionPerformed

    private void ButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAActionPerformed
        digita("A");
    }//GEN-LAST:event_ButtonAActionPerformed

    private void ButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBActionPerformed
        digita("B");
    }//GEN-LAST:event_ButtonBActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        digita("C");
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDActionPerformed
        digita("D");
    }//GEN-LAST:event_ButtonDActionPerformed

    private void ButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEActionPerformed
        digita("E");
    }//GEN-LAST:event_ButtonEActionPerformed

    private void ButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFActionPerformed
        digita("F");
    }//GEN-LAST:event_ButtonFActionPerformed

    private void ButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparActionPerformed
//        String textoResultado = Resultado.getText();
        Resultado.setText("0");
        ResultadoBin.setText("0");
        ResultadoHex.setText("0");
        ResultadoDec.setText("0");
        ResultadoOct.setText("0");
//        if(textoResultado.equals("0")) {
//            Calculos.setText("");
//            Resultado.setText("0");
//        } else {
//            Resultado.setText("0");
//        }
    }//GEN-LAST:event_ButtonLimparActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        digita("9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        digita("6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        digita("3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void ButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonApagarActionPerformed
        String textResultado = Resultado.getText();
        if(!textResultado.isEmpty()) {
           textResultado = textResultado.substring(0, textResultado.length() - 1);
           if(textResultado.isEmpty()) {
               textResultado = "0";
           }
           Resultado.setText(textResultado);
        }
    }//GEN-LAST:event_ButtonApagarActionPerformed

    private void ButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualActionPerformed
        ConversaoBase calculadora = new ConversaoBase(Resultado.getText(), baseSelecionada);
        ResultadoDec.setText(calculadora.Decimal(calculadora));
        ResultadoBin.setText(calculadora.Binario(calculadora));
        ResultadoOct.setText(calculadora.Octal(calculadora));
        ResultadoHex.setText(calculadora.Hexadecimal(calculadora));
    }//GEN-LAST:event_ButtonIgualActionPerformed

    private void ButtonHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHexActionPerformed
        baseSelecionada = 1;
        ButtonLimparActionPerformed(evt);
        ((AbstractDocument) Resultado.getDocument()).setDocumentFilter(new BaseDocumentFilter("[0-9A-Fa-f]+"));
        Status.setText("Convertendo Hexadecimal");

        ButtonA.setEnabled(true);
        ButtonB.setEnabled(true);
        ButtonC.setEnabled(true);
        ButtonD.setEnabled(true);
        ButtonE.setEnabled(true);
        ButtonF.setEnabled(true);
        Button7_.setEnabled(true);
        Button4_.setEnabled(true);
        Button1_.setEnabled(true);
        Button8_.setEnabled(true);
        Button5_.setEnabled(true);
        Button2_.setEnabled(true);
        Button0.setEnabled(true);
        ButtonLimpar.setEnabled(true);
        Button9.setEnabled(true);
        Button6.setEnabled(true);
        Button3.setEnabled(true);
    }//GEN-LAST:event_ButtonHexActionPerformed

    private void ButtonDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecActionPerformed
        baseSelecionada = 0;
        ButtonLimparActionPerformed(evt);
        Status.setText("Convertendo Decimal");
        ((AbstractDocument) Resultado.getDocument()).setDocumentFilter(new BaseDocumentFilter("[0-9]+"));
        
        ButtonA.setEnabled(false);
        ButtonB.setEnabled(false);
        ButtonC.setEnabled(false);
        ButtonD.setEnabled(false);
        ButtonE.setEnabled(false);
        ButtonF.setEnabled(false);
        Button7_.setEnabled(true);
        Button4_.setEnabled(true);
        Button1_.setEnabled(true);
        Button8_.setEnabled(true);
        Button5_.setEnabled(true);
        Button2_.setEnabled(true);
        Button0.setEnabled(true);
        ButtonLimpar.setEnabled(true);
        Button9.setEnabled(true);
        Button6.setEnabled(true);
        Button3.setEnabled(true);
    }//GEN-LAST:event_ButtonDecActionPerformed

    private void ButtonOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOctActionPerformed
        baseSelecionada = 2;
        ButtonLimparActionPerformed(evt);
        Status.setText("Convertendo Octal");
        ((AbstractDocument) Resultado.getDocument()).setDocumentFilter(new BaseDocumentFilter("[0-7]+"));
         
        ButtonA.setEnabled(false);
        ButtonB.setEnabled(false);
        ButtonC.setEnabled(false);
        ButtonD.setEnabled(false);
        ButtonE.setEnabled(false);
        ButtonF.setEnabled(false);
        Button7_.setEnabled(true);
        Button4_.setEnabled(true);
        Button1_.setEnabled(true);
        Button8_.setEnabled(false);
        Button5_.setEnabled(true);
        Button2_.setEnabled(true);
        Button0.setEnabled(true);
        ButtonLimpar.setEnabled(true);
        Button9.setEnabled(false);
        Button6.setEnabled(true);
        Button3.setEnabled(true);
    }//GEN-LAST:event_ButtonOctActionPerformed

    private void ButtonBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBinActionPerformed
        baseSelecionada = 3;
        ButtonLimparActionPerformed(evt);
        Status.setText("Convertendo Binário");
        ((AbstractDocument) Resultado.getDocument()).setDocumentFilter(new BaseDocumentFilter("[01]+"));

        ButtonA.setEnabled(false);
        ButtonB.setEnabled(false);
        ButtonC.setEnabled(false);
        ButtonD.setEnabled(false);
        ButtonE.setEnabled(false);
        ButtonF.setEnabled(false);
        Button7_.setEnabled(false);
        Button4_.setEnabled(false);
        Button1_.setEnabled(true);
        Button8_.setEnabled(false);
        Button5_.setEnabled(false);
        Button2_.setEnabled(false);
        Button0.setEnabled(true);
        ButtonLimpar.setEnabled(true);
        Button9.setEnabled(false);
        Button6.setEnabled(false);
        Button3.setEnabled(false);
    }//GEN-LAST:event_ButtonBinActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculadoraInterface calcInterface = new CalculadoraInterface();
                calcInterface.setVisible(true);
                calcInterface.ButtonDec.doClick();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1_;
    private javax.swing.JButton Button2_;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4_;
    private javax.swing.JButton Button5_;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7_;
    private javax.swing.JButton Button8_;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonA;
    private javax.swing.JButton ButtonApagar;
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonBin;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonDec;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton ButtonF;
    private javax.swing.JButton ButtonHex;
    private javax.swing.JButton ButtonIgual;
    private javax.swing.JButton ButtonLimpar;
    private javax.swing.JButton ButtonOct;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel ResultadoBin;
    private javax.swing.JLabel ResultadoDec;
    private javax.swing.JLabel ResultadoHex;
    private javax.swing.JLabel ResultadoOct;
    private javax.swing.JLabel Status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
